# Generated by Django 5.0.4 on 2024-04-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0002_remove_baby_name_baby_b_name_baby_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='b_name',
            new_name='name',
        ),
    ]
