# Generated by Django 4.2.11 on 2024-04-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0003_rename_b_name_baby_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=200, null=True)),
                ('timeIn', models.DateTimeField(blank=True, null=True)),
                ('timeOut', models.DateTimeField(blank=True, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=3, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name_plural': 'Babies'},
        ),
        migrations.AddField(
            model_name='sitter',
            name='timeIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitter',
            name='timeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SitterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('timeIn', models.DateTimeField(blank=True, null=True)),
                ('timeOut', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarApp.categorystay')),
            ],
        ),
    ]
