# Generated by Django 4.2.11 on 2024-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0004_babyregistration_doll_alter_baby_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterregistration',
            name='timeIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitterregistration',
            name='timeOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
