# Generated by Django 4.2.11 on 2024-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0005_alter_sitterregistration_timein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitterregistration',
            name='category',
        ),
        migrations.AddField(
            model_name='babyregistration',
            name='motherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
