# Generated by Django 4.2.11 on 2024-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0006_remove_sitterregistration_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='c_pay',
        ),
        migrations.AlterField(
            model_name='sitter',
            name='category',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], default=True, max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryStay',
        ),
    ]
