# Generated by Django 4.2.11 on 2024-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0007_remove_payment_c_pay_alter_sitter_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BabyRegistration',
        ),
        migrations.DeleteModel(
            name='SitterRegistration',
        ),
        migrations.AlterField(
            model_name='sitter',
            name='timeIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='timeOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
