# Generated by Django 4.2.11 on 2024-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0008_delete_babyregistration_delete_sitterregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
