# Generated by Django 4.2.11 on 2024-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0009_alter_baby_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='sponsor',
            new_name='father_name',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='timeIn',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='timeOut',
        ),
        migrations.AddField(
            model_name='baby',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
