# Generated by Django 4.2.11 on 2024-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0010_rename_sponsor_baby_father_name_remove_baby_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='father_name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
