# Generated by Django 4.2.11 on 2024-05-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0011_alter_baby_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
