# Generated by Django 4.2.13 on 2024-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0013_sitter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='next_of_kin',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
