# Generated by Django 4.2.13 on 2024-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0014_sitter_next_of_kin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='nin',
            field=models.CharField(default=True, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='recommender_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
