# Generated by Django 4.2.13 on 2024-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0016_sitter_level_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='sitter_number',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
