# Generated by Django 4.2.13 on 2024-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0017_sitter_sitter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
