# Generated by Django 4.2.13 on 2024-05-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0018_sitter_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='brought_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='time_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
