# Generated by Django 4.2.13 on 2024-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarApp', '0019_baby_brought_by_baby_time_of_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='baby_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='period_of_stay',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], default=True, max_length=8),
            preserve_default=False,
        ),
    ]
